//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ZetaResourceEditor.RuntimeBusinessLogic.AdService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdServiceSoap", Namespace="http://zeta-resource-editor.com/")]
    public partial class AdService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNextAdSimpleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNextAdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdService() {
            this.Url = "http://www.zeta-resource-editor.com/backend/AdService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNextAdSimpleCompletedEventHandler GetNextAdSimpleCompleted;
        
        /// <remarks/>
        public event GetNextAdCompletedEventHandler GetNextAdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://zeta-resource-editor.com/GetNextAdSimple", RequestNamespace="http://zeta-resource-editor.com/", ResponseNamespace="http://zeta-resource-editor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AdResponse GetNextAdSimple() {
            object[] results = this.Invoke("GetNextAdSimple", new object[0]);
            return ((AdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetNextAdSimpleAsync() {
            this.GetNextAdSimpleAsync(null);
        }
        
        /// <remarks/>
        public void GetNextAdSimpleAsync(object userState) {
            if ((this.GetNextAdSimpleOperationCompleted == null)) {
                this.GetNextAdSimpleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNextAdSimpleOperationCompleted);
            }
            this.InvokeAsync("GetNextAdSimple", new object[0], this.GetNextAdSimpleOperationCompleted, userState);
        }
        
        private void OnGetNextAdSimpleOperationCompleted(object arg) {
            if ((this.GetNextAdSimpleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNextAdSimpleCompleted(this, new GetNextAdSimpleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://zeta-resource-editor.com/GetNextAd", RequestNamespace="http://zeta-resource-editor.com/", ResponseNamespace="http://zeta-resource-editor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AdResponse GetNextAd(AdRequest request) {
            object[] results = this.Invoke("GetNextAd", new object[] {
                        request});
            return ((AdResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetNextAdAsync(AdRequest request) {
            this.GetNextAdAsync(request, null);
        }
        
        /// <remarks/>
        public void GetNextAdAsync(AdRequest request, object userState) {
            if ((this.GetNextAdOperationCompleted == null)) {
                this.GetNextAdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNextAdOperationCompleted);
            }
            this.InvokeAsync("GetNextAd", new object[] {
                        request}, this.GetNextAdOperationCompleted, userState);
        }
        
        private void OnGetNextAdOperationCompleted(object arg) {
            if ((this.GetNextAdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNextAdCompleted(this, new GetNextAdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zeta-resource-editor.com/")]
    public partial class AdResponse {
        
        private string textField;
        
        private string urlField;
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://zeta-resource-editor.com/")]
    public partial class AdRequest {
        
        private int cultureField;
        
        /// <remarks/>
        public int Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetNextAdSimpleCompletedEventHandler(object sender, GetNextAdSimpleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNextAdSimpleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNextAdSimpleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetNextAdCompletedEventHandler(object sender, GetNextAdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNextAdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNextAdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AdResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AdResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591