global using JetBrains.Annotations;
global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Zeta.VoyagerLibrary.Core.Logging;
global using ZetaShortPaths;
