//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZetaResourceEditor.RuntimeBusinessLogic.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new global::System.Resources.ResourceManager("ZetaResourceEditor.RuntimeBusinessLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client ID.
        /// </summary>
        internal static string BingSoapTranslationEngine_AppID1Name_Client_ID
        {
            get
            {
                return ResourceManager.GetString("BingSoapTranslationEngine_AppID1Name_Client_ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client secret.
        /// </summary>
        internal static string BingSoapTranslationEngine_AppID2Name_Client_secret
        {
            get
            {
                return ResourceManager.GetString("BingSoapTranslationEngine_AppID2Name_Client_secret", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator (Bing).
        /// </summary>
        internal static string BingSoapTranslationEngine_UserReadableName_Microsoft_Translator__Bing_
        {
            get
            {
                return ResourceManager.GetString("BingSoapTranslationEngine_UserReadableName_Microsoft_Translator__Bing_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No access token value can be read from access token..
        /// </summary>
        internal static string BingTranslationHelper_GetAccessToken_No_access_token_value_can_be_read_from_access_token_
        {
            get
            {
                return ResourceManager.GetString("BingTranslationHelper_GetAccessToken_No_access_token_value_can_be_read_from_acces" +
                        "s_token_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No expiration date can be read from access token..
        /// </summary>
        internal static string BingTranslationHelper_GetAccessToken_No_expiration_date_can_be_read_from_access_token_
        {
            get
            {
                return ResourceManager.GetString("BingTranslationHelper_GetAccessToken_No_expiration_date_can_be_read_from_access_t" +
                        "oken_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping Excel document &apos;{0}&apos; because it contains no work sheets..
        /// </summary>
        internal static string ExcelExportController_doProcess_Skipping_Excel_document___0___because_it_contains_no_work_sheets_
        {
            get
            {
                return ResourceManager.GetString("ExcelExportController_doProcess_Skipping_Excel_document___0___because_it_contains" +
                        "_no_work_sheets_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skipping Microsoft Office Excel document..
        /// </summary>
        internal static string ExcelExportController_doProcess_Skipping_Microsoft_Office_Excel_document_
        {
            get
            {
                return ResourceManager.GetString("ExcelExportController_doProcess_Skipping_Microsoft_Office_Excel_document_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sending {0} files through Zeta Uploader....
        /// </summary>
        internal static string ExcelExportController_doSendFilesWithZetaUploader_Sending__0__files_through_Zeta_Uploader___
        {
            get
            {
                return ResourceManager.GetString("ExcelExportController_doSendFilesWithZetaUploader_Sending__0__files_through_Zeta_" +
                        "Uploader___", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reference tag name must be provided but is currently NULL or empty..
        /// </summary>
        internal static string ExcelImportController_getDestinationTableRowsByTagName_Reference_tag_name_must_be_provided_but_is_currently_NULL_or_empty_
        {
            get
            {
                return ResourceManager.GetString("ExcelImportController_getDestinationTableRowsByTagName_Reference_tag_name_must_be" +
                        "_provided_but_is_currently_NULL_or_empty_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Neither name column nor reference language column present..
        /// </summary>
        internal static string ExcelImportController_processWorkSheetFileIntelligent_Neither_name_column_nor_reference_language_column_present_
        {
            get
            {
                return ResourceManager.GetString("ExcelImportController_processWorkSheetFileIntelligent_Neither_name_column_nor_ref" +
                        "erence_language_column_present_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saving file {0} of {1}....
        /// </summary>
        internal static string ExcelImportController_processWorkSheetFileIntelligent_Saving_file__0__of__1____
        {
            get
            {
                return ResourceManager.GetString("ExcelImportController_processWorkSheetFileIntelligent_Saving_file__0__of__1____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to generate unique file names..
        /// </summary>
        internal static string FailedToGenerateUniqueFileNames
        {
            get
            {
                return ResourceManager.GetString("FailedToGenerateUniqueFileNames", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatic translation exists.
        /// </summary>
        internal static string FileGroupStates_AutomaticTranslationsExist
        {
            get
            {
                return ResourceManager.GetString("FileGroupStates_AutomaticTranslationsExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completely translated.
        /// </summary>
        internal static string FileGroupStates_CompletelyTranslated
        {
            get
            {
                return ResourceManager.GetString("FileGroupStates_CompletelyTranslated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No strings.
        /// </summary>
        internal static string FileGroupStates_Empty
        {
            get
            {
                return ResourceManager.GetString("FileGroupStates_Empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (Some) completely empty rows.
        /// </summary>
        internal static string FileGroupStates_EmptyRows
        {
            get
            {
                return ResourceManager.GetString("FileGroupStates_EmptyRows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Different number of format parameters.
        /// </summary>
        internal static string FileGroupStates_FormatParameterMismatches
        {
            get
            {
                return ResourceManager.GetString("FileGroupStates_FormatParameterMismatches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Translations are missing.
        /// </summary>
        internal static string FileGroupStates_TranslationsMissing
        {
            get
            {
                return ResourceManager.GetString("FileGroupStates_TranslationsMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to App ID.
        /// </summary>
        internal static string GoogleRestfulTranslationEngine_AppID1Name_App_ID
        {
            get
            {
                return ResourceManager.GetString("GoogleRestfulTranslationEngine_AppID1Name_App_ID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Translate.
        /// </summary>
        internal static string GoogleRestfulTranslationEngine_UserReadableName_Google_Translate
        {
            get
            {
                return ResourceManager.GetString("GoogleRestfulTranslationEngine_UserReadableName_Google_Translate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Translate.
        /// </summary>
        internal static string GoogleScreenScrapingTranslationEngine_UserReadableName_Google_Translate
        {
            get
            {
                return ResourceManager.GetString("GoogleScreenScrapingTranslationEngine_UserReadableName_Google_Translate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google does not provide a language code for the culture &apos;{0}&apos; to translate..
        /// </summary>
        internal static string GoogleTranslationHelper_doMapCultureToLanguageCode_Google_does_not_provide_a_language_code_for_the_culture___0___to_translate_
        {
            get
            {
                return ResourceManager.GetString("GoogleTranslationHelper_doMapCultureToLanguageCode_Google_does_not_provide_a_lang" +
                        "uage_code_for_the_culture___0___to_translate_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No culture for culture name &apos;{0}&apos; available..
        /// </summary>
        internal static string LanguageCodeDetection_MakeValidCulture_No_culture_for_culture_name___0___available_
        {
            get
            {
                return ResourceManager.GetString("LanguageCodeDetection_MakeValidCulture_No_culture_for_culture_name___0___availabl" +
                        "e_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Microsoft Translator (Bing) does not provide a language code for the culture &apos;{0}&apos; to translate..
        /// </summary>
        internal static string NoLangForBing
        {
            get
            {
                return ResourceManager.GetString("NoLangForBing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No files to send..
        /// </summary>
        internal static string SendProjectController_doSendFilesWithZetaUploader_No_files_to_send_
        {
            get
            {
                return ResourceManager.GetString("SendProjectController_doSendFilesWithZetaUploader_No_files_to_send_", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Zeta Resource Editor support.
        /// </summary>
        internal static string SendProjectController_VendorReceiverGuiName_Zeta_Resource_Editor_support
        {
            get
            {
                return ResourceManager.GetString("SendProjectController_VendorReceiverGuiName_Zeta_Resource_Editor_support", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string SR_ColumnCaption_Comment
        {
            get
            {
                return ResourceManager.GetString("SR_ColumnCaption_Comment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File group.
        /// </summary>
        internal static string SR_ColumnCaption_FileGroup
        {
            get
            {
                return ResourceManager.GetString("SR_ColumnCaption_FileGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SR_ColumnCaption_Name
        {
            get
            {
                return ResourceManager.GetString("SR_ColumnCaption_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reference language value must be provided but is currently NULL or empty..
        /// </summary>
        internal static string SR_CommandProcessorReceive_getTableRows_Reference_language_value
        {
            get
            {
                return ResourceManager.GetString("SR_CommandProcessorReceive_getTableRows_Reference_language_value", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing work sheet {0} of {1}, row {2} of {3} ({4}%)..
        /// </summary>
        internal static string SR_CommandProcessorReceive_Process_ProcessingWorkSheetOfRowOf
        {
            get
            {
                return ResourceManager.GetString("SR_CommandProcessorReceive_Process_ProcessingWorkSheetOfRowOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string SR_CommandProcessorSend_Process_Comment
        {
            get
            {
                return ResourceManager.GetString("SR_CommandProcessorSend_Process_Comment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string SR_CommandProcessorSend_Process_Group
        {
            get
            {
                return ResourceManager.GetString("SR_CommandProcessorSend_Process_Group", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SR_CommandProcessorSend_Process_Name
        {
            get
            {
                return ResourceManager.GetString("SR_CommandProcessorSend_Process_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Processing file group {0} of {1}, row {2} of {3} ({4}%)..
        /// </summary>
        internal static string SR_CommandProcessorSend_Process_ProcessingFileGroupOfRowOf
        {
            get
            {
                return ResourceManager.GetString("SR_CommandProcessorSend_Process_ProcessingFileGroupOfRowOf", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saving Microsoft Office Excel document....
        /// </summary>
        internal static string SR_CommandProcessorSend_Process_SavingMicrosoftOfficeExcelDocument
        {
            get
            {
                return ResourceManager.GetString("SR_CommandProcessorSend_Process_SavingMicrosoftOfficeExcelDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ZRE Export.
        /// </summary>
        internal static string SR_CommandProcessorSend_Process_ZRE_Export
        {
            get
            {
                return ResourceManager.GetString("SR_CommandProcessorSend_Process_ZRE_Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save operation was cancelled at file &apos;{0}&apos;..
        /// </summary>
        internal static string SR_DataProcessing_storeFiles_Save_operation_was_cancelled_at_file
        {
            get
            {
                return ResourceManager.GetString("SR_DataProcessing_storeFiles_Save_operation_was_cancelled_at_file", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Saving failed because of read-only file &apos;{0}&apos;..
        /// </summary>
        internal static string SR_DataProcessing_storeFiles_Saving_failed_because_of_read_only_file
        {
            get
            {
                return ResourceManager.GetString("SR_DataProcessing_storeFiles_Saving_failed_because_of_read_only_file", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New file name does not match required pattern for this file group. Needs &apos;{0}&apos; as the base name and &apos;{1}&apos; as the base extension..
        /// </summary>
        internal static string SR_FileGroup_CreateAndAddNewFile_New_file_name_does_not_match
        {
            get
            {
                return ResourceManager.GetString("SR_FileGroup_CreateAndAddNewFile_New_file_name_does_not_match", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (unnamed).
        /// </summary>
        internal static string SR_FileGroup_NameIntelli_Unnamed
        {
            get
            {
                return ResourceManager.GetString("SR_FileGroup_NameIntelli_Unnamed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pattern &apos;{0}&apos;/&apos;{1}&apos; doesn&apos;t match &apos;{2}&apos;..
        /// </summary>
        internal static string SR_LanguageCodeDetection_extractBlock_PatternDoesNotMatch
        {
            get
            {
                return ResourceManager.GetString("SR_LanguageCodeDetection_extractBlock_PatternDoesNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Freeware license.
        /// </summary>
        internal static string SR_LicenseType_Freeware
        {
            get
            {
                return ResourceManager.GetString("SR_LicenseType_Freeware", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .NET resource files.
        /// </summary>
        internal static string SR_NetResourceFileAccessor_Name_NETResourceFiles
        {
            get
            {
                return ResourceManager.GetString("SR_NetResourceFileAccessor_Name_NETResourceFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to QT resource files.
        /// </summary>
        internal static string SR_QTResourceFileAccessor_Name_QTResourceFiles
        {
            get
            {
                return ResourceManager.GetString("SR_QTResourceFileAccessor_Name_QTResourceFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ask whether to overwrite read-only files.
        /// </summary>
        internal static string SR_ReadOnlyFileOverwriteBehaviour_Ask
        {
            get
            {
                return ResourceManager.GetString("SR_ReadOnlyFileOverwriteBehaviour_Ask", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fail when trying to overwrite read-only files.
        /// </summary>
        internal static string SR_ReadOnlyFileOverwriteBehaviour_Fail
        {
            get
            {
                return ResourceManager.GetString("SR_ReadOnlyFileOverwriteBehaviour_Fail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overwrite read-only files.
        /// </summary>
        internal static string SR_ReadOnlyFileOverwriteBehaviour_Overwrite
        {
            get
            {
                return ResourceManager.GetString("SR_ReadOnlyFileOverwriteBehaviour_Overwrite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip read-only files.
        /// </summary>
        internal static string SR_ReadOnlyFileOverwriteBehaviour_Skip
        {
            get
            {
                return ResourceManager.GetString("SR_ReadOnlyFileOverwriteBehaviour_Skip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (Auto detect).
        /// </summary>
        internal static string SR_TranslationHelper_GetSourceLanguages_AutoDetect
        {
            get
            {
                return ResourceManager.GetString("SR_TranslationHelper_GetSourceLanguages_AutoDetect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The HTML code returned from Google appears to have changed. Please check for an updated version of Zeta Resource Editor..
        /// </summary>
        internal static string SR_TranslationHelper_parseRawPageContent_GoogleCodeChanged
        {
            get
            {
                return ResourceManager.GetString("SR_TranslationHelper_parseRawPageContent_GoogleCodeChanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string SR_ZreLicenseType_LicenseType_Category
        {
            get
            {
                return ResourceManager.GetString("SR_ZreLicenseType_LicenseType_Category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specify the type of the license..
        /// </summary>
        internal static string SR_ZreLicenseType_LicenseType_Description
        {
            get
            {
                return ResourceManager.GetString("SR_ZreLicenseType_LicenseType_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to License type.
        /// </summary>
        internal static string SR_ZreLicenseType_LicenseType_DisplayName
        {
            get
            {
                return ResourceManager.GetString("SR_ZreLicenseType_LicenseType_DisplayName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Taking snapshot {0} of {1} for file group &apos;{2}&apos;....
        /// </summary>
        internal static string TakeFullSnapshot
        {
            get
            {
                return ResourceManager.GetString("TakeFullSnapshot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Taking snapshots..
        /// </summary>
        internal static string TakingSnapshots
        {
            get
            {
                return ResourceManager.GetString("TakingSnapshots", resourceCulture);
            }
        }
    }
}
