//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZetaResourceEditor.RuntimeBusinessLogic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.zeta-resource-editor.com/backend/AdService.asmx")]
        public string ZetaResourceEditor_RuntimeBusinessLogic_AdService_AdService {
            get {
                return ((string)(this["ZetaResourceEditor_RuntimeBusinessLogic_AdService_AdService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.zeta-resource-editor.com/backend/TranslationService.asmx")]
        public string ZetaResourceEditor_RuntimeBusinessLogic_TranslationService_TranslationService {
            get {
                return ((string)(this["ZetaResourceEditor_RuntimeBusinessLogic_TranslationService_TranslationService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.zeta-resource-editor.com/backend/UpdateCheckerService.asmx")]
        public string ZetaResourceEditor_RuntimeBusinessLogic_UpdateChecker_UpdateCheckerService {
            get {
                return ((string)(this["ZetaResourceEditor_RuntimeBusinessLogic_UpdateChecker_UpdateCheckerService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.zeta-uploader.com/WebServices/ZetaUploaderCommunication.asmx")]
        public string ZetaResourceEditor_RuntimeBusinessLogic_ZetaUploader_ZetaUploaderCommunication {
            get {
                return ((string)(this["ZetaResourceEditor_RuntimeBusinessLogic_ZetaUploader_ZetaUploaderCommunication"]));
            }
        }
    }
}
