//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace ZetaResourceEditor.RuntimeBusinessLogic.TranslationService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TranslationServiceSoap", Namespace="http://www.zeta-resource-editor.com/")]
    public partial class TranslationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllSourceTranslationModesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDestinationTranslationModesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSelfTranslationInformationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TranslationService() {
            this.Url = "http://www.zeta-resource-editor.com/backend/TranslationService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllSourceTranslationModesCompletedEventHandler GetAllSourceTranslationModesCompleted;
        
        /// <remarks/>
        public event GetAllDestinationTranslationModesCompletedEventHandler GetAllDestinationTranslationModesCompleted;
        
        /// <remarks/>
        public event GetSelfTranslationInformationCompletedEventHandler GetSelfTranslationInformationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zeta-resource-editor.com/GetAllSourceTranslationModes", RequestNamespace="http://www.zeta-resource-editor.com/", ResponseNamespace="http://www.zeta-resource-editor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TranslationMode3[] GetAllSourceTranslationModes() {
            object[] results = this.Invoke("GetAllSourceTranslationModes", new object[0]);
            return ((TranslationMode3[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllSourceTranslationModesAsync() {
            this.GetAllSourceTranslationModesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllSourceTranslationModesAsync(object userState) {
            if ((this.GetAllSourceTranslationModesOperationCompleted == null)) {
                this.GetAllSourceTranslationModesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSourceTranslationModesOperationCompleted);
            }
            this.InvokeAsync("GetAllSourceTranslationModes", new object[0], this.GetAllSourceTranslationModesOperationCompleted, userState);
        }
        
        private void OnGetAllSourceTranslationModesOperationCompleted(object arg) {
            if ((this.GetAllSourceTranslationModesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSourceTranslationModesCompleted(this, new GetAllSourceTranslationModesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zeta-resource-editor.com/GetAllDestinationTranslationModes", RequestNamespace="http://www.zeta-resource-editor.com/", ResponseNamespace="http://www.zeta-resource-editor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TranslationMode3[] GetAllDestinationTranslationModes() {
            object[] results = this.Invoke("GetAllDestinationTranslationModes", new object[0]);
            return ((TranslationMode3[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDestinationTranslationModesAsync() {
            this.GetAllDestinationTranslationModesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllDestinationTranslationModesAsync(object userState) {
            if ((this.GetAllDestinationTranslationModesOperationCompleted == null)) {
                this.GetAllDestinationTranslationModesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDestinationTranslationModesOperationCompleted);
            }
            this.InvokeAsync("GetAllDestinationTranslationModes", new object[0], this.GetAllDestinationTranslationModesOperationCompleted, userState);
        }
        
        private void OnGetAllDestinationTranslationModesOperationCompleted(object arg) {
            if ((this.GetAllDestinationTranslationModesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDestinationTranslationModesCompleted(this, new GetAllDestinationTranslationModesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.zeta-resource-editor.com/GetSelfTranslationInformation", RequestNamespace="http://www.zeta-resource-editor.com/", ResponseNamespace="http://www.zeta-resource-editor.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SelfTranslationInformation GetSelfTranslationInformation() {
            object[] results = this.Invoke("GetSelfTranslationInformation", new object[0]);
            return ((SelfTranslationInformation)(results[0]));
        }
        
        /// <remarks/>
        public void GetSelfTranslationInformationAsync() {
            this.GetSelfTranslationInformationAsync(null);
        }
        
        /// <remarks/>
        public void GetSelfTranslationInformationAsync(object userState) {
            if ((this.GetSelfTranslationInformationOperationCompleted == null)) {
                this.GetSelfTranslationInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSelfTranslationInformationOperationCompleted);
            }
            this.InvokeAsync("GetSelfTranslationInformation", new object[0], this.GetSelfTranslationInformationOperationCompleted, userState);
        }
        
        private void OnGetSelfTranslationInformationOperationCompleted(object arg) {
            if ((this.GetSelfTranslationInformationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSelfTranslationInformationCompleted(this, new GetSelfTranslationInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zeta-resource-editor.com/")]
    public partial class TranslationMode3 {
        
        private string languageCodeField;
        
        /// <remarks/>
        public string LanguageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.zeta-resource-editor.com/")]
    public partial class SelfTranslationInformation {
        
        private string googleUrlField;
        
        private string googleRefererUrlField;
        
        private string parseRegexPatternField;
        
        private string httpPostDataField;
        
        /// <remarks/>
        public string GoogleUrl {
            get {
                return this.googleUrlField;
            }
            set {
                this.googleUrlField = value;
            }
        }
        
        /// <remarks/>
        public string GoogleRefererUrl {
            get {
                return this.googleRefererUrlField;
            }
            set {
                this.googleRefererUrlField = value;
            }
        }
        
        /// <remarks/>
        public string ParseRegexPattern {
            get {
                return this.parseRegexPatternField;
            }
            set {
                this.parseRegexPatternField = value;
            }
        }
        
        /// <remarks/>
        public string HttpPostData {
            get {
                return this.httpPostDataField;
            }
            set {
                this.httpPostDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllSourceTranslationModesCompletedEventHandler(object sender, GetAllSourceTranslationModesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSourceTranslationModesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllSourceTranslationModesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TranslationMode3[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TranslationMode3[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllDestinationTranslationModesCompletedEventHandler(object sender, GetAllDestinationTranslationModesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDestinationTranslationModesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDestinationTranslationModesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TranslationMode3[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TranslationMode3[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSelfTranslationInformationCompletedEventHandler(object sender, GetSelfTranslationInformationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSelfTranslationInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSelfTranslationInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SelfTranslationInformation Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SelfTranslationInformation)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591