//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZetaResourceEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZetaResourceEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the base folder where to create the files..
        /// </summary>
        internal static string AddNewFileGroupForm_baseFolderSelectButton_Click_Please_select_the_base_folder_where_to_create_the_files_ {
            get {
                return ResourceManager.GetString("AddNewFileGroupForm_baseFolderSelectButton_Click_Please_select_the_base_folder_wh" +
                        "ere_to_create_the_files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your translation API keys are not yet set. In order to use the translation feature, please fill them first.
        ///
        ///Do you want to fill them now?.
        /// </summary>
        internal static string AutoTranslateForm_CheckShowAppIDsMissing {
            get {
                return ResourceManager.GetString("AutoTranslateForm_CheckShowAppIDsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google and Microsoft Bing changed their translation services. Do you want to read how you can continue using Google Translate and Bing Translate?.
        /// </summary>
        internal static string AutoTranslateForm_CheckShowNewTranslationInfos_Google_changed_their_translation_settings__Do_you_want_to_read_how_you_can_continue_using_Google_Translate_ {
            get {
                return ResourceManager.GetString("AutoTranslateForm_CheckShowNewTranslationInfos_Google_changed_their_translation_s" +
                        "ettings__Do_you_want_to_read_how_you_can_continue_using_Google_Translate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource file for the language you selected was already present and simply was added, but not created..
        /// </summary>
        internal static string CreateNewFileForm_buttonOK_Click_The_resource_file_for_the_language_you_selected_was_already_present_and_simply_was_added__but_not_created_ {
            get {
                return ResourceManager.GetString("CreateNewFileForm_buttonOK_Click_The_resource_file_for_the_language_you_selected_" +
                        "was_already_present_and_simply_was_added__but_not_created_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings occurred..
        /// </summary>
        internal static string ExcelExportWizardForm_progressBackgroundWorker_RunWorkerCompleted_Warnings_occurred_ {
            get {
                return ResourceManager.GetString("ExcelExportWizardForm_progressBackgroundWorker_RunWorkerCompleted_Warnings_occurr" +
                        "ed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving files, please wait….
        /// </summary>
        internal static string ResourceEditorUserControl_DoSaveFiles_Saving_files__please_wait___ {
            get {
                return ResourceManager.GetString("ResourceEditorUserControl_DoSaveFiles_Saving_files__please_wait___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update, please wait….
        /// </summary>
        internal static string SetupDownloadController_DownloadAndRunSetup_Downloading_update__please_wait___ {
            get {
                return ResourceManager.GetString("SetupDownloadController_DownloadAndRunSetup_Downloading_update__please_wait___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sign_warning {
            get {
                object obj = ResourceManager.GetObject("sign_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://zeta.li/zre-ENU-home.
        /// </summary>
        internal static string SR_AboutForm_linkLabel1LinkClicked_Httpwwwzetasoftwaredelinkszrehome {
            get {
                return ResourceManager.GetString("SR_AboutForm_linkLabel1LinkClicked_Httpwwwzetasoftwaredelinkszrehome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your own Website in 10 Minutes - Zeta Producer CMS.
        /// </summary>
        internal static string SR_AdService_stockResponses_ZetaProducer {
            get {
                return ResourceManager.GetString("SR_AdService_stockResponses_ZetaProducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Management Software - For Test Cases and Test Plan Templates.
        /// </summary>
        internal static string SR_AdService_stockResponses_ZetaTest {
            get {
                return ResourceManager.GetString("SR_AdService_stockResponses_ZetaTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily send large files to your contacts - Zeta Uploader.
        /// </summary>
        internal static string SR_AdService_stockResponses_ZetaUploader {
            get {
                return ResourceManager.GetString("SR_AdService_stockResponses_ZetaUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished translating. Translated {0} texts. {1} translations successful, {2} translations failed..
        /// </summary>
        internal static string SR_AutoTranslateForm_buttonTranslateClick_TranslatingTranslatedTexts {
            get {
                return ResourceManager.GetString("SR_AutoTranslateForm_buttonTranslateClick_TranslatingTranslatedTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} texts were translated by using already translated other texts..
        /// </summary>
        internal static string SR_AutoTranslateForm_buttonTranslateClick_TranslatingTranslatedTextsExisting {
            get {
                return ResourceManager.GetString("SR_AutoTranslateForm_buttonTranslateClick_TranslatingTranslatedTextsExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background processing did not respond within the given time-frame..
        /// </summary>
        internal static string SR_BackgroundWorkerLongProgressForm_cancelGuardTimerTick_NotResponding {
            get {
                return ResourceManager.GetString("SR_BackgroundWorkerLongProgressForm_cancelGuardTimerTick_NotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during processing..
        /// </summary>
        internal static string SR_BackgroundWorkerLongProgressGui_DefaultRunWorkerCompleted_ErrorDuringProcessing {
            get {
                return ResourceManager.GetString("SR_BackgroundWorkerLongProgressGui_DefaultRunWorkerCompleted_ErrorDuringProcessin" +
                        "g", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string SR_ColumnCaption_Comment {
            get {
                return ResourceManager.GetString("SR_ColumnCaption_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel the export?.
        /// </summary>
        internal static string SR_ConfirmCancelExport {
            get {
                return ResourceManager.GetString("SR_ConfirmCancelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to cancel the import?.
        /// </summary>
        internal static string SR_ConfirmCancelImport {
            get {
                return ResourceManager.GetString("SR_ConfirmCancelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new files….
        /// </summary>
        internal static string SR_CreateNewFilesForm_Creating {
            get {
                return ResourceManager.GetString("SR_CreateNewFilesForm_Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation finished successfully, however no files were created, because the language already exists for all affected file groups..
        /// </summary>
        internal static string SR_CreateNewFilesForm_Finished01 {
            get {
                return ResourceManager.GetString("SR_CreateNewFilesForm_Finished01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation finished successfully. {0} new files were created, {1} new files were not created (because the language already exists for all affected file groups)..
        /// </summary>
        internal static string SR_CreateNewFilesForm_Finished02 {
            get {
                return ResourceManager.GetString("SR_CreateNewFilesForm_Finished02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation finished successfully. {0} new files were created..
        /// </summary>
        internal static string SR_CreateNewFilesForm_Finished03 {
            get {
                return ResourceManager.GetString("SR_CreateNewFilesForm_Finished03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation finished successfully. {0} new files were created, of which {1} files were already present and were simple added, but not created..
        /// </summary>
        internal static string SR_CreateNewFilesForm_Finished04 {
            get {
                return ResourceManager.GetString("SR_CreateNewFilesForm_Finished04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder to store the project to..
        /// </summary>
        internal static string SR_CreateNewProjectForm_browseToolStripMenuItemClick_TheProjectTo {
            get {
                return ResourceManager.GetString("SR_CreateNewProjectForm_browseToolStripMenuItemClick_TheProjectTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeta Resource Editor projects.
        /// </summary>
        internal static string SR_CreateNewProjectForm_CreateNewProjectFormLoad_ZetaResourceEditorProjects {
            get {
                return ResourceManager.GetString("SR_CreateNewProjectForm_CreateNewProjectFormLoad_ZetaResourceEditorProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///	&lt;!-- 
        ///		Microsoft ResX Schema
        ///
        ///		Version 1.3
        ///
        ///		The primary goals of this format is to allow a simple XML format 
        ///		that is mostly human readable. The generation and parsing of the 
        ///		various data types are done through the TypeConverter classes 
        ///		associated with the data types.
        ///
        ///		Example:
        ///
        ///		... ado.net/XML headers &amp; schema ...
        ///		&lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///		&lt;resheader name=&quot;version&quot;&gt;1.3&lt;/resheader&gt;
        ///		&lt;resh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SR_EmptyResourceFile {
            get {
                return ResourceManager.GetString("SR_EmptyResourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T must be an enumeration..
        /// </summary>
        internal static string SR_EnumComboBox_Initialize_TMustBeAnEnum {
            get {
                return ResourceManager.GetString("SR_EnumComboBox_Initialize_TMustBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to quit the application?.
        /// </summary>
        internal static string SR_ErrorForm_button2Click_QuitTheApplication {
            get {
                return ResourceManager.GetString("SR_ErrorForm_button2Click_QuitTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception details.
        /// </summary>
        internal static string SR_ErrorForm_inspectTheUnderlyingExceptionToolStripMenuItemClick_ExceptionDetails {
            get {
                return ResourceManager.GetString("SR_ErrorForm_inspectTheUnderlyingExceptionToolStripMenuItemClick_ExceptionDetails" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel documents (*.xlsx)|*.xlsx.
        /// </summary>
        internal static string SR_ExportWizard_buttonBrowseClick_ExcelFilesXlsxls {
            get {
                return ResourceManager.GetString("SR_ExportWizard_buttonBrowseClick_ExcelFilesXlsxls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected condition during Excel export file path suggestion..
        /// </summary>
        internal static string SR_ExportWizardForm_buttonDecorateAutomatically_Click_Unexpected_condition {
            get {
                return ResourceManager.GetString("SR_ExportWizardForm_buttonDecorateAutomatically_Click_Unexpected_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeta Resource Editor project file.
        /// </summary>
        internal static string SR_Host_Main_ZetaResourceEditorProjectFile {
            get {
                return ResourceManager.GetString("SR_Host_Main_ZetaResourceEditorProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Office Excel documents (*.xlsx).
        /// </summary>
        internal static string SR_ImportExportWizard_buttonBrowseFileClick_ExcelFilesXls {
            get {
                return ResourceManager.GetString("SR_ImportExportWizard_buttonBrowseFileClick_ExcelFilesXls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export translation files into a Microsoft Office Excel document for external translation..
        /// </summary>
        internal static string SR_ImportExportWizard_printDescriptionText_Translation {
            get {
                return ResourceManager.GetString("SR_ImportExportWizard_printDescriptionText_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Excel document was successfully created.
        ///
        ///Do you want to open the Excel document now?.
        /// </summary>
        internal static string SR_ImportExportWizard_wizardFinishButtonClick_ExcelDocumentNow {
            get {
                return ResourceManager.GetString("SR_ImportExportWizard_wizardFinishButtonClick_ExcelDocumentNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A total of {0} rows were imported..
        /// </summary>
        internal static string SR_ImportWizardForm_progressBackgroundWorker_RunWorkerCompleted_Result {
            get {
                return ResourceManager.GetString("SR_ImportWizardForm_progressBackgroundWorker_RunWorkerCompleted_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.zeta-resource-editor.com/inline-news.html.
        /// </summary>
        internal static string SR_InlineNewsUrl {
            get {
                return ResourceManager.GetString("SR_InlineNewsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Auto detect).
        /// </summary>
        internal static string SR_Language_Auto {
            get {
                return ResourceManager.GetString("SR_Language_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zre-donate-one-usd.
        /// </summary>
        internal static string SR_MainForm_buttonDonateOne_ItemClick_zre_donate_one_currency {
            get {
                return ResourceManager.GetString("SR_MainForm_buttonDonateOne_ItemClick_zre_donate_one_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite the read-only file &apos;{0}&apos;?.
        /// </summary>
        internal static string SR_MainForm_dataProcessing_CanOverwrite_Do_you_want_to_overwrite_the_read_only_file___0___ {
            get {
                return ResourceManager.GetString("SR_MainForm_dataProcessing_CanOverwrite_Do_you_want_to_overwrite_the_read_only_fi" +
                        "le___0___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the tag and all of its translations?.
        /// </summary>
        internal static string SR_MainForm_deleteTagToolStripMenuItemClick_DoYouReallyWantToDeleteTheTagAndAllOfItsTranslations {
            get {
                return ResourceManager.GetString("SR_MainForm_deleteTagToolStripMenuItemClick_DoYouReallyWantToDeleteTheTagAndAllOf" +
                        "ItsTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to the resource files?.
        /// </summary>
        internal static string SR_MainForm_DoSaveFiles_SaveChangesToTheResourceFiles {
            get {
                return ResourceManager.GetString("SR_MainForm_DoSaveFiles_SaveChangesToTheResourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource files.
        /// </summary>
        internal static string SR_MainForm_openToolStripMenuItemClick_ResourceFiles {
            get {
                return ResourceManager.GetString("SR_MainForm_openToolStripMenuItemClick_ResourceFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide project panel.
        /// </summary>
        internal static string SR_MainForm_UpdateUI_HideProjectPanel {
            get {
                return ResourceManager.GetString("SR_MainForm_UpdateUI_HideProjectPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show project panel.
        /// </summary>
        internal static string SR_MainForm_UpdateUI_ShowProjectPanel {
            get {
                return ResourceManager.GetString("SR_MainForm_UpdateUI_ShowProjectPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear recent files list.
        /// </summary>
        internal static string SR_MainFormNew_loadMruFileFiles_ClearRecentFilesList {
            get {
                return ResourceManager.GetString("SR_MainFormNew_loadMruFileFiles_ClearRecentFilesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear recent projects list.
        /// </summary>
        internal static string SR_MainFormNew_loadMruFileProjects_ClearRecentProjectsList {
            get {
                return ResourceManager.GetString("SR_MainFormNew_loadMruFileProjects_ClearRecentProjectsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes all items from the list above.
        /// </summary>
        internal static string SR_MainFormNew_loadMruFileProjects_RemovesAllItemsFromTheListAbove {
            get {
                return ResourceManager.GetString("SR_MainFormNew_loadMruFileProjects_RemovesAllItemsFromTheListAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://zeta.li/zre-ENU-purchase-license.
        /// </summary>
        internal static string SR_OptionsForm_purchaseLicenseButton_Click {
            get {
                return ResourceManager.GetString("SR_OptionsForm_purchaseLicenseButton_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Invalid license key).
        /// </summary>
        internal static string SR_OptionsForm_updateLicenseInfo__Invalid_license_key_ {
            get {
                return ResourceManager.GetString("SR_OptionsForm_updateLicenseInfo__Invalid_license_key_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only add files that are from the same folder as the files that are already present..
        /// </summary>
        internal static string SR_ProjectFilesUserControl_AddFilesToFileGroupWithDialog_AlreadyPresent {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_AddFilesToFileGroupWithDialog_AlreadyPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files you try to add already exists in the project..
        /// </summary>
        internal static string SR_ProjectFilesUserControl_AddResourceFilesWithDialog_ExistsInTheProject {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_AddResourceFilesWithDialog_ExistsInTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the base folder to add from. Resources in child folders will be added automatically..
        /// </summary>
        internal static string SR_ProjectFilesUserControl_AutomaticallyAddAddResourceFilesWithDialog_AddedAutomatically {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_AutomaticallyAddAddResourceFilesWithDialog_AddedAutoma" +
                        "tically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing. {0} file groups with a total of {1} files were added..
        /// </summary>
        internal static string SR_ProjectFilesUserControl_AutomaticallyAddAddResourceFilesWithDialog_OfFilesWereAdded {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_AutomaticallyAddAddResourceFilesWithDialog_OfFilesWere" +
                        "Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished processing. No file groups were added..
        /// </summary>
        internal static string SR_ProjectFilesUserControl_AutomaticallyAddAddResourceFilesWithDialog_WereAdded {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_AutomaticallyAddAddResourceFilesWithDialog_WereAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the files will be added….
        /// </summary>
        internal static string SR_ProjectFilesUserControl_AutomaticallyAddAddResourceFilesWithDialog_WillBeAdded {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_AutomaticallyAddAddResourceFilesWithDialog_WillBeAdded" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New project folder.
        /// </summary>
        internal static string SR_ProjectFilesUserControl_buttonAddProjectFolderItemClick_NewProjectFolder {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_buttonAddProjectFolderItemClick_NewProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove the select project folder and all contained file groups from the project?.
        /// </summary>
        internal static string SR_ProjectFilesUserControl_buttonRemoveProjectFolder_ItemClick {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_buttonRemoveProjectFolder_ItemClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes to the project file?.
        /// </summary>
        internal static string SR_ProjectFilesUserControl_DoSaveFile_SaveChangesToTheProjectFile {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_DoSaveFile_SaveChangesToTheProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeta Resource Editor project files.
        /// </summary>
        internal static string SR_ProjectFilesUserControl_OpenWithDialog_EditorProjectFiles {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_OpenWithDialog_EditorProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove the selected file from the file group?.
        /// </summary>
        internal static string SR_ProjectFilesUserControl_RemoveFileFromFileGroupWithDialog_FromTheFileGroup {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_RemoveFileFromFileGroupWithDialog_FromTheFileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected node type &apos;{0}&apos; while removing..
        /// </summary>
        internal static string SR_ProjectFilesUserControl_removeNodeAndchilds_Unexpected_node_type {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_removeNodeAndchilds_Unexpected_node_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove the selected file group from the project?.
        /// </summary>
        internal static string SR_ProjectFilesUserControl_RemoveResourceFilesWithDialog_FromTheProject {
            get {
                return ResourceManager.GetString("SR_ProjectFilesUserControl_RemoveResourceFilesWithDialog_FromTheProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root.
        /// </summary>
        internal static string SR_ProjectFolder_RootName_Root {
            get {
                return ResourceManager.GetString("SR_ProjectFolder_RootName_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The items were sent successfully to Zeta Software. Thank you!.
        /// </summary>
        internal static string SR_ReportItemsForm_buttonOKClick_ThankYou {
            get {
                return ResourceManager.GetString("SR_ReportItemsForm_buttonOKClick_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text was not found..
        /// </summary>
        internal static string SR_ResourceEditorUserControl_Find_TheTextWasNotFound {
            get {
                return ResourceManager.GetString("SR_ResourceEditorUserControl_Find_TheTextWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio solutions, C# projects.
        /// </summary>
        internal static string SR_SlnNames {
            get {
                return ResourceManager.GetString("SR_SlnNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string SR_Test {
            get {
                return ResourceManager.GetString("SR_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define a semicolon separated list of optional default types that can be used for the &quot;[optionaldefaulttypes]&quot; placeholder.
        ///
        ///The default types will be ignores during file type parsing for generating new files and language detection.
        ///
        ///E.g. &quot;.aspx;.ascx;.asmx;.master&quot;
        ///
        ///Always include the dot for each type..
        /// </summary>
        internal static string SR_toolTipItem4Text {
            get {
                return ResourceManager.GetString("SR_toolTipItem4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the fowllowing (optional) placeholders:
        ///
        ///- &quot;[basename]&quot; (no dot)
        ///- &quot;[languagecode]&quot; (no dot)
        ///- &quot;[extension]&quot; (dot excluded)
        ///- &quot;[optionaldefaulttypes]&quot; (dot included)
        ///
        ///e.g. &quot;[basename][optionaldefaulttypes].[languagecode].[extension]&quot;.
        /// </summary>
        internal static string SR_toolTipItem5Text {
            get {
                return ResourceManager.GetString("SR_toolTipItem5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the fowllowing (optional) placeholders:
        ///
        ///- &quot;[basename]&quot; (no dot)
        ///- &quot;[languagecode]&quot; (no dot)
        ///- &quot;[extension]&quot; (dot excluded)
        ///- &quot;[optionaldefaulttypes]&quot; (dot included)
        ///
        ///e.g. &quot;[basename][optionaldefaulttypes].[extension]&quot;.
        /// </summary>
        internal static string SR_toolTipItem6Text {
            get {
                return ResourceManager.GetString("SR_toolTipItem6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the allowed optional default types..
        /// </summary>
        internal static string SR_toolTipTitleItem4Text {
            get {
                return ResourceManager.GetString("SR_toolTipTitleItem4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the file name pattern for non-neutral languages..
        /// </summary>
        internal static string SR_toolTipTitleItem5Text {
            get {
                return ResourceManager.GetString("SR_toolTipTitleItem5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines the file name pattern for the neutral language..
        /// </summary>
        internal static string SR_toolTipTitleItem6Text {
            get {
                return ResourceManager.GetString("SR_toolTipTitleItem6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Auto detect).
        /// </summary>
        internal static string SR_TranslationHelper_GetSourceLanguages_AutoDetect {
            get {
                return ResourceManager.GetString("SR_TranslationHelper_GetSourceLanguages_AutoDetect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Visual Studio solution or project file.
        /// </summary>
        internal static string SR_VSDialogTitle {
            get {
                return ResourceManager.GetString("SR_VSDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Zeta Resource Editor] 404 Error occurred.
        /// </summary>
        internal static string Str_404EMailMessageSubject {
            get {
                return ResourceManager.GetString("Str_404EMailMessageSubject", resourceCulture);
            }
        }
    }
}
