//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateCheckInfo2", Namespace="http://www.zeta-resource-editor.com/")]
    public partial class UpdateCheckInfo2 : object
    {
        
        private string ApiKeyField;
        
        private System.DateTime VersionDateField;
        
        private string VersionNumberField;
        
        private int CultureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ApiKey
        {
            get
            {
                return this.ApiKeyField;
            }
            set
            {
                this.ApiKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime VersionDate
        {
            get
            {
                return this.VersionDateField;
            }
            set
            {
                this.VersionDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string VersionNumber
        {
            get
            {
                return this.VersionNumberField;
            }
            set
            {
                this.VersionNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Culture
        {
            get
            {
                return this.CultureField;
            }
            set
            {
                this.CultureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdatePresentResult2", Namespace="http://www.zeta-resource-editor.com/")]
    public partial class UpdatePresentResult2 : object
    {
        
        private bool IsPresentField;
        
        private string DownloadWebsiteUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsPresent
        {
            get
            {
                return this.IsPresentField;
            }
            set
            {
                this.IsPresentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DownloadWebsiteUrl
        {
            get
            {
                return this.DownloadWebsiteUrlField;
            }
            set
            {
                this.DownloadWebsiteUrlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateInformationResult2", Namespace="http://www.zeta-resource-editor.com/")]
    public partial class UpdateInformationResult2 : object
    {
        
        private string ApiKeyField;
        
        private bool IsPresentField;
        
        private string FileNameField;
        
        private byte[] FileContentField;
        
        private string AlternativeFallbackDownloadUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ApiKey
        {
            get
            {
                return this.ApiKeyField;
            }
            set
            {
                this.ApiKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsPresent
        {
            get
            {
                return this.IsPresentField;
            }
            set
            {
                this.IsPresentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] FileContent
        {
            get
            {
                return this.FileContentField;
            }
            set
            {
                this.FileContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AlternativeFallbackDownloadUrl
        {
            get
            {
                return this.AlternativeFallbackDownloadUrlField;
            }
            set
            {
                this.AlternativeFallbackDownloadUrlField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.zeta-resource-editor.com/", ConfigurationName="ServiceReference1.UpdateCheckerServiceSoap")]
    public interface UpdateCheckerServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name info from namespace http://www.zeta-resource-editor.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zeta-resource-editor.com/IsUpdateAvailable2", ReplyAction="*")]
        ServiceReference1.IsUpdateAvailable2Response IsUpdateAvailable2(ServiceReference1.IsUpdateAvailable2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zeta-resource-editor.com/IsUpdateAvailable2", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.IsUpdateAvailable2Response> IsUpdateAvailable2Async(ServiceReference1.IsUpdateAvailable2Request request);
        
        // CODEGEN: Generating message contract since element name info from namespace http://www.zeta-resource-editor.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zeta-resource-editor.com/DownloadUpdate2", ReplyAction="*")]
        ServiceReference1.DownloadUpdate2Response DownloadUpdate2(ServiceReference1.DownloadUpdate2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zeta-resource-editor.com/DownloadUpdate2", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.DownloadUpdate2Response> DownloadUpdate2Async(ServiceReference1.DownloadUpdate2Request request);
        
        // CODEGEN: Generating message contract since element name assemblyVersion from namespace http://www.zeta-resource-editor.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zeta-resource-editor.com/IsUpdateAvailable", ReplyAction="*")]
        ServiceReference1.IsUpdateAvailableResponse IsUpdateAvailable(ServiceReference1.IsUpdateAvailableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.zeta-resource-editor.com/IsUpdateAvailable", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.IsUpdateAvailableResponse> IsUpdateAvailableAsync(ServiceReference1.IsUpdateAvailableRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUpdateAvailable2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdateAvailable2", Namespace="http://www.zeta-resource-editor.com/", Order=0)]
        public ServiceReference1.IsUpdateAvailable2RequestBody Body;
        
        public IsUpdateAvailable2Request()
        {
        }
        
        public IsUpdateAvailable2Request(ServiceReference1.IsUpdateAvailable2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.zeta-resource-editor.com/")]
    public partial class IsUpdateAvailable2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UpdateCheckInfo2 info;
        
        public IsUpdateAvailable2RequestBody()
        {
        }
        
        public IsUpdateAvailable2RequestBody(ServiceReference1.UpdateCheckInfo2 info)
        {
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUpdateAvailable2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdateAvailable2Response", Namespace="http://www.zeta-resource-editor.com/", Order=0)]
        public ServiceReference1.IsUpdateAvailable2ResponseBody Body;
        
        public IsUpdateAvailable2Response()
        {
        }
        
        public IsUpdateAvailable2Response(ServiceReference1.IsUpdateAvailable2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.zeta-resource-editor.com/")]
    public partial class IsUpdateAvailable2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UpdatePresentResult2 IsUpdateAvailable2Result;
        
        public IsUpdateAvailable2ResponseBody()
        {
        }
        
        public IsUpdateAvailable2ResponseBody(ServiceReference1.UpdatePresentResult2 IsUpdateAvailable2Result)
        {
            this.IsUpdateAvailable2Result = IsUpdateAvailable2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadUpdate2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadUpdate2", Namespace="http://www.zeta-resource-editor.com/", Order=0)]
        public ServiceReference1.DownloadUpdate2RequestBody Body;
        
        public DownloadUpdate2Request()
        {
        }
        
        public DownloadUpdate2Request(ServiceReference1.DownloadUpdate2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.zeta-resource-editor.com/")]
    public partial class DownloadUpdate2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UpdateCheckInfo2 info;
        
        public DownloadUpdate2RequestBody()
        {
        }
        
        public DownloadUpdate2RequestBody(ServiceReference1.UpdateCheckInfo2 info)
        {
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadUpdate2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadUpdate2Response", Namespace="http://www.zeta-resource-editor.com/", Order=0)]
        public ServiceReference1.DownloadUpdate2ResponseBody Body;
        
        public DownloadUpdate2Response()
        {
        }
        
        public DownloadUpdate2Response(ServiceReference1.DownloadUpdate2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.zeta-resource-editor.com/")]
    public partial class DownloadUpdate2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.UpdateInformationResult2 DownloadUpdate2Result;
        
        public DownloadUpdate2ResponseBody()
        {
        }
        
        public DownloadUpdate2ResponseBody(ServiceReference1.UpdateInformationResult2 DownloadUpdate2Result)
        {
            this.DownloadUpdate2Result = DownloadUpdate2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUpdateAvailableRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdateAvailable", Namespace="http://www.zeta-resource-editor.com/", Order=0)]
        public ServiceReference1.IsUpdateAvailableRequestBody Body;
        
        public IsUpdateAvailableRequest()
        {
        }
        
        public IsUpdateAvailableRequest(ServiceReference1.IsUpdateAvailableRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.zeta-resource-editor.com/")]
    public partial class IsUpdateAvailableRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string assemblyVersion;
        
        public IsUpdateAvailableRequestBody()
        {
        }
        
        public IsUpdateAvailableRequestBody(string assemblyVersion)
        {
            this.assemblyVersion = assemblyVersion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUpdateAvailableResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdateAvailableResponse", Namespace="http://www.zeta-resource-editor.com/", Order=0)]
        public ServiceReference1.IsUpdateAvailableResponseBody Body;
        
        public IsUpdateAvailableResponse()
        {
        }
        
        public IsUpdateAvailableResponse(ServiceReference1.IsUpdateAvailableResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.zeta-resource-editor.com/")]
    public partial class IsUpdateAvailableResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IsUpdateAvailableResult;
        
        public IsUpdateAvailableResponseBody()
        {
        }
        
        public IsUpdateAvailableResponseBody(string IsUpdateAvailableResult)
        {
            this.IsUpdateAvailableResult = IsUpdateAvailableResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface UpdateCheckerServiceSoapChannel : ServiceReference1.UpdateCheckerServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class UpdateCheckerServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.UpdateCheckerServiceSoap>, ServiceReference1.UpdateCheckerServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UpdateCheckerServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(UpdateCheckerServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), UpdateCheckerServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UpdateCheckerServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UpdateCheckerServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UpdateCheckerServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UpdateCheckerServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UpdateCheckerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.IsUpdateAvailable2Response ServiceReference1.UpdateCheckerServiceSoap.IsUpdateAvailable2(ServiceReference1.IsUpdateAvailable2Request request)
        {
            return base.Channel.IsUpdateAvailable2(request);
        }
        
        public ServiceReference1.UpdatePresentResult2 IsUpdateAvailable2(ServiceReference1.UpdateCheckInfo2 info)
        {
            ServiceReference1.IsUpdateAvailable2Request inValue = new ServiceReference1.IsUpdateAvailable2Request();
            inValue.Body = new ServiceReference1.IsUpdateAvailable2RequestBody();
            inValue.Body.info = info;
            ServiceReference1.IsUpdateAvailable2Response retVal = ((ServiceReference1.UpdateCheckerServiceSoap)(this)).IsUpdateAvailable2(inValue);
            return retVal.Body.IsUpdateAvailable2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.IsUpdateAvailable2Response> ServiceReference1.UpdateCheckerServiceSoap.IsUpdateAvailable2Async(ServiceReference1.IsUpdateAvailable2Request request)
        {
            return base.Channel.IsUpdateAvailable2Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.IsUpdateAvailable2Response> IsUpdateAvailable2Async(ServiceReference1.UpdateCheckInfo2 info)
        {
            ServiceReference1.IsUpdateAvailable2Request inValue = new ServiceReference1.IsUpdateAvailable2Request();
            inValue.Body = new ServiceReference1.IsUpdateAvailable2RequestBody();
            inValue.Body.info = info;
            return ((ServiceReference1.UpdateCheckerServiceSoap)(this)).IsUpdateAvailable2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.DownloadUpdate2Response ServiceReference1.UpdateCheckerServiceSoap.DownloadUpdate2(ServiceReference1.DownloadUpdate2Request request)
        {
            return base.Channel.DownloadUpdate2(request);
        }
        
        public ServiceReference1.UpdateInformationResult2 DownloadUpdate2(ServiceReference1.UpdateCheckInfo2 info)
        {
            ServiceReference1.DownloadUpdate2Request inValue = new ServiceReference1.DownloadUpdate2Request();
            inValue.Body = new ServiceReference1.DownloadUpdate2RequestBody();
            inValue.Body.info = info;
            ServiceReference1.DownloadUpdate2Response retVal = ((ServiceReference1.UpdateCheckerServiceSoap)(this)).DownloadUpdate2(inValue);
            return retVal.Body.DownloadUpdate2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.DownloadUpdate2Response> ServiceReference1.UpdateCheckerServiceSoap.DownloadUpdate2Async(ServiceReference1.DownloadUpdate2Request request)
        {
            return base.Channel.DownloadUpdate2Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.DownloadUpdate2Response> DownloadUpdate2Async(ServiceReference1.UpdateCheckInfo2 info)
        {
            ServiceReference1.DownloadUpdate2Request inValue = new ServiceReference1.DownloadUpdate2Request();
            inValue.Body = new ServiceReference1.DownloadUpdate2RequestBody();
            inValue.Body.info = info;
            return ((ServiceReference1.UpdateCheckerServiceSoap)(this)).DownloadUpdate2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceReference1.IsUpdateAvailableResponse ServiceReference1.UpdateCheckerServiceSoap.IsUpdateAvailable(ServiceReference1.IsUpdateAvailableRequest request)
        {
            return base.Channel.IsUpdateAvailable(request);
        }
        
        public string IsUpdateAvailable(string assemblyVersion)
        {
            ServiceReference1.IsUpdateAvailableRequest inValue = new ServiceReference1.IsUpdateAvailableRequest();
            inValue.Body = new ServiceReference1.IsUpdateAvailableRequestBody();
            inValue.Body.assemblyVersion = assemblyVersion;
            ServiceReference1.IsUpdateAvailableResponse retVal = ((ServiceReference1.UpdateCheckerServiceSoap)(this)).IsUpdateAvailable(inValue);
            return retVal.Body.IsUpdateAvailableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.IsUpdateAvailableResponse> ServiceReference1.UpdateCheckerServiceSoap.IsUpdateAvailableAsync(ServiceReference1.IsUpdateAvailableRequest request)
        {
            return base.Channel.IsUpdateAvailableAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.IsUpdateAvailableResponse> IsUpdateAvailableAsync(string assemblyVersion)
        {
            ServiceReference1.IsUpdateAvailableRequest inValue = new ServiceReference1.IsUpdateAvailableRequest();
            inValue.Body = new ServiceReference1.IsUpdateAvailableRequestBody();
            inValue.Body.assemblyVersion = assemblyVersion;
            return ((ServiceReference1.UpdateCheckerServiceSoap)(this)).IsUpdateAvailableAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UpdateCheckerServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.UpdateCheckerServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.UpdateCheckerServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.zeta-resource-editor.com/backend/UpdateCheckerService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.UpdateCheckerServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.zeta-resource-editor.com/backend/UpdateCheckerService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            UpdateCheckerServiceSoap,
            
            UpdateCheckerServiceSoap12,
        }
    }
}
